apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend-podinfo #Matches the labels of frontend pod
    pod-template-hash: "664ddc9d84" #Matches the labels of frontend pod
  ports:
    - protocol: TCP
      port: 80 # Incoming traffic on port 80 (from WITHIN the cluster) will be directed to port 9898 on the selected pods. From Inside of the cluster network you can reach the Application on port 80
      targetPort: 9898  # Links to frontend pod. 
      nodePort: 30000 # Exposes host. For outside of the cluster. Outside of the cluster network you can reach the Application on port 30000
